# Generated by Django 2.2.8 on 2021-03-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AddField(
            model_name='department',
            name='floor_number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Numero de piso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='office_number',
            field=models.PositiveSmallIntegerField(verbose_name='Numero de Oficina'),
        ),
    ]
