# Generated by Django 2.2.8 on 2021-03-01 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0002_auto_20210301_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='name_department',
        ),
    ]
