# Generated by Django 2.2.8 on 2021-03-01 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
