# Generated by Django 2.2.8 on 2021-03-01 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
