# Generated by Django 2.2.8 on 2021-02-28 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_remove_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='direccion',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='telefono',
            new_name='phone_number',
        ),
    ]
