# Generated by Django 2.2.8 on 2021-03-01 23:33

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0005_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=stdimage.models.StdImageField(default='usuarios/avatar.png', upload_to='usuarios/'),
        ),
    ]
