# Generated by Django 2.2.8 on 2021-03-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0005_auto_20210228_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('office_number', models.IntegerField(verbose_name='Numero de Oficina')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamento',
            },
        ),
    ]
