# Generated by Django 2.2.8 on 2021-03-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0006_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nombre'),
        ),
    ]
