# Generated by Django 2.2.8 on 2021-03-01 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0007_auto_20210228_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='custom_user.Department', verbose_name='Departamento'),
            preserve_default=False,
        ),
    ]
